dist: xenial
language: node_js
node_js:
  - "12"
  - "10"
  - "8"
services:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services
  # https://benlimmer.com/2019/01/14/travis-ci-xvfb/
  - xvfb

before_install:
  - curl --location http://rawgit.com/twolfson/fix-travis-ci/master/lib/install.sh | bash -s

notifications:
  email:
    recipients:
      - todd@twolfson.com
    on_success: change
    on_failure: change
